# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "Hello My pipeline id is << pipeline.id >> and my git branch is << pipeline.git.branch >>."
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world!."
      - run:
          name: "Print env var that is part of our project"
          command: |
            echo $GA_NAME
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
